---
title: "Courses"
toc: true
---

## M.A. Economics

- Mathematical Economics

- Economics Analytics

- Advanced Microeconomics Analysis

- Advanced Macroeconomic Analysis - [**Course Project**](https://drive.google.com/file/d/1xOzh2XVb4oOf3VBJDbIZqwCGrVGf28Ck/view?usp=sharing){target="_blank"}

- Health Economics: A Global Perspective - [**Course Project**](https://drive.google.com/drive/folders/1S3quhZk68JUyILzZGUae-Fi40Tgz4_Zn?usp=drive_link){target="_blank"}

- Supply Chain management - **Course Project**

- Prescriptive Analytics of Management Science - **Course Project**

- Econometrics I - [**Course Project**](https://drive.google.com/file/d/1BYpL_ddcK0vDFuNU3hy6cx7PJ4IGFFdM/view?usp=drive_link){target="_blank"}

- Econometrics II - **Course Project**

- Econometrics III - **Course Project**

- Research Methods (Capstone) - **Course Project**

\n\n

## Courses (Online)

**Business Analytics with Excel - Johns Hopkins University**

- Business Analytics with Excel: Elementary to Advanced - [**Certificate**](https://drive.google.com/file/d/11fO8X6U93i2-dGafk67WXLEITkv8YWWU/view?usp=sharing){target="_blank"}

- Business Analytics with Excel: Intermediate to Advanced

- Advanced Business Analytics: Excel Optimization & Simulation

**Google Digital Marketing & E-commerce**

- Foundations of Digital Marketing and E-commerce - [**Certificate**](https://drive.google.com/file/d/1FTzsP_m_8rSOFBlYkPJ_btr8dJneqOag/view?usp=drive_link){target="_blank"}

- Attract and Engage Customers with Digital Marketing - [**Certificate**](https://drive.google.com/file/d/1a5D8kjLnw54um3rsaXdNHTHaG4pEIbtM/view?usp=drive_link){target="_blank"}

- From Likes to Leads: Interact with Customers Online

**Introduction to Healthcare - Stanford University**

- Introduction to Healthcare - [**Certificate**](https://drive.google.com/file/d/1saDWXQIrpM60N38bZomJJ_Q11jE4BGhJ/view?usp=drive_link){target="_blank"}
